# Rustfmt configuration
# https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"

# Imports (stable options)
reorder_imports = true
reorder_modules = true
